background_opacity          0.75
window_padding_width        15

font_family JetBrainsMonoNerdFontMono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0

cursor_shape beam
cursor_beam_thickness 1.5
cursor_stop_blinking_after 0
cursor_trail                1

allow_remote_control yes
enable_audio_bell no

scrollback_lines 10000
# todo: scrollback pager?

momentum_scroll 1

url_style double

confirm_os_window_close 0

# todo: finish this config

include themes/noctalia.conf
